### ISSUE TITLE
How to name the yml config file?

### ISSUE THREAD

**Issue by nicorikken** [chaoss/MARS#16]
Running through the install process, I'm stuck at the yml config file. There seems to be no filename documented (like `config.yml`) in the main README and the active_user_input README. In the step of actually running MARS, I see no YAML file provided as input, so I cannot derive it from there.

I would love it if there was a `whatevername.yml.example` or `whatevername.example.yml` file in the directory with the same content as in the active_user_input README. Then I could just copy the file by stripping out the `.example` part from the filename and fill in the details to have it run.

For now I'll have a look through the source code if a certain filename is expected.

**Comment by yash2002109** [comment]
Hi @nicorikken,

The YAML file exists in the `active_user_input` directory : https://github.com/chaoss/MARS/blob/main/automation-english/active_user_input/working-groups-config.yml

We do provide a template on how to add information to the YAML file: https://github.com/chaoss/MARS/tree/main/automation-english/active_user_input#file-structure

We use the specific name `working-groups-config.yml` as the input to the scripts.

**Comment by ritik-malik** [comment]
Hi @nicorikken ,
The yml config file location is intentionally missing from the main README, since the automation system is only ready for the English release, and we'll be requiring a separate yml file for the translations one. When that will be done, we plan to describe both of them in the main README.

Then main README will be updated once we finalize some decisions on the translation automation process. As said in the mail, you can refer to this [README](https://github.com/chaoss/MARS/blob/main/automation-english/README.md) in the [`automation-english`](https://github.com/chaoss/MARS/tree/main/automation-english) directory for the english release. There it will point you to the correct location of the yml file and how to configure it. It is located in the [active_user_input](https://github.com/chaoss/MARS/tree/main/automation-english/active_user_input) directory

**Comment by nicorikken** [comment]
Reading through the code I came to the same conclusion, it is already configured and on the correct location. The documentation confused me a bit at the moment as it stated I needed to do something, but it wasn't clear what to do.

**Comment by ritik-malik** [comment]
What we "need to do", is to update the yml file with new metrics before every release. But since it is already updated, we preferred to skip this step in user testing.
Talking of "how" to update it, we have this separate [README](https://github.com/chaoss/MARS/blob/main/automation-english/active_user_input/README.md) which defines the file structure and how to tweak it accordingly.

**Comment by nicorikken** [comment]
Check
